# This folder is cached between builds
cache:
  paths:
    - node_modules/
    
build_branch:
  stage: build
  image: node:latest
  tags:
    - dev
  before_script:
    - npm config set user node
    - npm config set unsafe-perm=true
    - npm install

  script:
    - npm run build


build_prod:
  stage: build
  image: node:latest
  when: manual
  only:
    - master
  tags:
    - prod
  before_script:
    - apt-get update && apt-get install rsync -y
    - npm config set user node
    - npm config set unsafe-perm=true

    - npm install

  script:
    - npm run build
    - rsync -rav --delete . /out/
